web:
  restart: always
  build: ./
  links:
    - redis:redis
  command: gunicorn --workers 2 --bind 0.0.0.0:5000 -m 007 draft:app
  volumes:
    - .:/usr/src/app

nginx:
  restart: always
  build: ./docker/nginx
  ports:
    - "80:80"
  links:
    - web:web

redis:
  restart: always
  image: redis:3.2-alpine

