version: "3"
services:

  web:
    restart: always
    build: ./
    depends_on:
      - nginx
      - redis
    links:
      - redis:redis
    command: gunicorn --workers 2 --bind 0.0.0.0:5000 -m 007 draft:app
    volumes:
      - .:/usr/src/app

  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    links:
      - web:web

  compass:
    restart: 'no'
    build: ./docker/compass
    command: bash -c 'cd /usr/src/app && compass compile -e production --force'
    volumes:
      - .:/usr/src/app

  redis:
    image: redis:3.2-alpine
